apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: angular-11
  title: Angular 11 template
  description: Create a new Angular project
  tags:
    - experimental
    - angular
spec:
  owner: web@example.com
  templater: ng
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description: Unique name of the component. Lowercase, URL-safe characters only.
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.