apiVersion: backstage.io/v1alpha1
kind: Template
# some metadata about the template itself
metadata:
  name: angular-11
  title: Angular 11
  description: Scaffolder for Angular 11
  tags:
    - recommended
    - angular
spec:
  owner: nobody
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.

  # these are the steps which are rendered in the frontend with the form input
  # parameters:
  #   - title: Fill in some steps
  #     required:
  #       - name
  #     properties:
  #       name:
  #         title: Name
  #         type: string
  #         description: Unique name of the component
  #         ui:autofocus: true
  #         ui:options:
  #           rows: 5
  #   - title: Choose a location
  #     required:
  #       - repoUrl
  #     properties:
  #       repoUrl:
  #         title: Repository Location
  #         type: string
  #         ui:field: RepoUrlPicker
  #         ui:options:
  #           allowedHosts:
  #             - gitlab.apsmos.com.com

  # # here's the steps that are executed in series in the scaffolder backend
  # steps:
    # - id: fetch-base
    #   name: Fetch Base
    #   action: fetch:cookiecutter
    #   input:
    #     url: ./template
    #     values:
    #       name: '{{ parameters.name }}'

    # - id: fetch-docs
    #   name: Fetch Docs
    #   action: fetch:plain
    #   input:
    #     targetPath: ./community
    #     url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: 'This is {{ parameters.name }}'
    #     repoUrl: '{{ parameters.repoUrl }}'

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
    #     catalogInfoPath: '/catalog-info.yaml'