apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: angular-11
  title: Angular 11 template
  description: Create a new Angular project
  tags:
    - experimental
    - angular
spec:
  owner: web@example.com
  templater: cra
  type: website
  path: '.'
  
  schema:
    required: 
      - component_id
      - use_typescript
      - description
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description: Unique name of the component. Lowercase, URL-safe characters only.
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.
      use_typescript:
        title:  Use TypeScript
        type: boolean
        description: Include TypeScript
        default: true
      use_github_actions:
        title:  Use Github Actions workflows to build this component
        type: boolean
        description: Use Github Actions
        default: true